repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.9.7  # Use the version of Ruff you have installed
    hooks:
      - id: ruff
        args: ["--fix"]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/kynan/nbstripout
    rev: 0.5.0
    hooks:
      - id: nbstripout
