repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.10.0  # Match this to your installed version of Ruff
    hooks:
      - id: ruff
        args: ["--fix"]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0  # Latest stable version after autoupdate
    hooks:
      - id: check-added-large-files
        args: ["--maxkb=500"]  # Disallow files larger than 500 KB
      - id: trailing-whitespace  # Remove trailing whitespace from files

  - repo: https://github.com/kynan/nbstripout
    rev: 0.8.1  # Updated revision from autoupdate
    hooks:
      - id: nbstripout  # Strip output cells from Jupyter notebooks
