# Dockerfile.mlflow
FROM python:3.9

# Install MLflow and dependencies
RUN pip install mlflow[extras]

# Install psycopg2 for PostgreSQL support
RUN pip install psycopg2-binary

# Expose port for MLflow UI
EXPOSE 5000

# Run MLflow
CMD ["mlflow", "ui", "--host", "0.0.0.0"]
