# Start from a base Python 3.9 image
FROM python:3.9

# Install MLflow and extra dependencies
RUN pip install mlflow[extras]

# Install psycopg2 for PostgreSQL support
RUN pip install psycopg2-binary

# Expose port for MLflow UI
EXPOSE 5000

# Run MLflow UI
CMD ["mlflow", "ui", "--host", "0.0.0.0"]
