
services:
  fastapi_app:
    build:
      context: .
      dockerfile: Dockerfile.fastapi
    container_name: fastapi_service
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://mlflow:mlflow@db:5432/mlflow_db
      - MLFLOW_TRACKING_URI=http://mlflow_service:5000
    depends_on:
      - db
      - mlflow_service
      - drift_monitoring_service  # Ensure FastAPI starts only after drift monitoring is up
    volumes:
      - .:/app
    command: uvicorn deploy_model:app --host 0.0.0.0 --port 8000

  drift_monitoring_service:
    build:
      context: .
      dockerfile: Dockerfile.drift_monitoring
    container_name: drift_monitoring_service
    ports:
      - "8085:8085"
    depends_on:
      - db
      - mlflow_service
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow_service:5000
      - DATA_PATH=/app/data/processed/predictive_maintenance_processed.csv
    volumes:
      - .:/app
    command: uvicorn src.monitoring.drift_monitoring:app --host 0.0.0.0 --port 8085 --reload

  mlflow_service:
    build:
      context: .
      dockerfile: Dockerfile.mlflow
    container_name: mlflow_service
    ports:
      - "5000:5000"
    environment:
      - MLFLOW_BACKEND_STORE_URI=postgresql://mlflow:mlflow@db:5432/mlflow_db
      - MLFLOW_ARTIFACT_URI=/mlflow
    volumes:
      - mlflow_data:/mlflow

  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: mlflow
      POSTGRES_PASSWORD: mlflow
      POSTGRES_DB: mlflow_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  dagster_service:
    build:
      context: .
      dockerfile: Dockerfile.dagster
    container_name: dagster_service
    ports:
      - "3000:3000"
    environment:
      - DAGSTER_HOME=/dagster_home
    volumes:
      - ./dagster_home:/dagster_home
      - ./src:/app/src
    command: ["dagit", "-h", "0.0.0.0", "-p", "3000"]

volumes:
  mlflow_data:
  postgres_data:
  dagster_home:
