version: "3.8"

services:
  fastapi_app:
    build:
      context: .
      dockerfile: Dockerfile.fastapi
    container_name: fastapi_service
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://mlflow:mlflow@db:5432/mlflow_db
      - MLFLOW_TRACKING_URI=http://mlflow_service:5000
    depends_on:
      - db
      - mlflow_service
    volumes:
      - .:/app  # Ensure your FastAPI app is mounted
    command: uvicorn deploy_model:app --host 0.0.0.0 --port 8000

  mlflow_service:
    build:
      context: .
      dockerfile: Dockerfile.mlflow
    container_name: mlflow_service
    ports:
      - "5000:5000"
    environment:
      - MLFLOW_BACKEND_STORE_URI=postgresql://mlflow:mlflow@db:5432/mlflow_db
      - MLFLOW_ARTIFACT_URI=/mlflow
    volumes:
      - mlflow_data:/mlflow  # Mount volume for persistent data storage

  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: mlflow
      POSTGRES_PASSWORD: mlflow
      POSTGRES_DB: mlflow_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Mount volume for persistent database storage

  dagster_service:
    build:
      context: .
      dockerfile: Dockerfile.dagster
    container_name: dagster_service
    ports:
      - "3000:3000"
    environment:
      - DAGSTER_HOME=/dagster_home
    volumes:
      - ./dagster_home:/dagster_home
      - ./src:/app/src
    command: ["dagster-webserver", "-h", "0.0.0.0", "-p", "3000"]  # Ensure Dagster web interface runs with dagster-webserver

volumes:
  mlflow_data:
  postgres_data:
  dagster_home:
