services:
  fastapi_app:
    build:
      context: .
      dockerfile: Dockerfile.fastapi
    container_name: fastapi_service
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://mlflow:mlflow@db:5432/mlflow_db
      - MLFLOW_TRACKING_URI=http://mlflow_service:5000
    depends_on:
      - db
      - mlflow_service
    volumes:
      - .:/app
    command: uvicorn deploy_model:app --host 0.0.0.0 --port 8000

  mlflow_service:
    build:
      context: .
      dockerfile: Dockerfile.mlflow
    container_name: mlflow_service
    ports:
      - "5000:5000"
    environment:
      - MLFLOW_BACKEND_STORE_URI=postgresql://mlflow:mlflow@db:5432/mlflow_db
      - MLFLOW_ARTIFACT_URI=/mlflow
    volumes:
      - mlflow_data:/mlflow

  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: mlflow
      POSTGRES_PASSWORD: mlflow
      POSTGRES_DB: mlflow_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  dagster:
    image: dagster/dagster-k8s:latest  
    container_name: dagster_service
    ports:
      - "3000:3000"
    environment:
      - DAGSTER_HOME=/dagster_home
    volumes:
      - ./dagster_home:/dagster_home  

volumes:
  mlflow_data:
  postgres_data:
  dagster_home:
