name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install uv, pre-commit, and pytest
        run: |
          python -m pip install --upgrade pip
          pip install uv pre-commit pytest

      - name: Install dependencies with uv
        run: uv sync

      - name: Debug: List installed packages (filter for pandas)
        run: .venv/bin/pip freeze | grep pandas

      - name: Run pre-commit hooks
        run: .venv/bin/pre-commit run --all-files

      - name: Run Pytest
        run: .venv/bin/pytest --maxfail=1 --disable-warnings -q
