name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install uv pre-commit pytest
          uv sync

      - name: Run Pre-commit Hooks
        run: pre-commit run --all-files

      - name: Run Pytest
        run: pytest --maxfail=1 --disable-warnings -q
