name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: Run pre-commit hooks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: Install uv and pre-commit
        run: |
          python -m pip install --upgrade pip
          pip install uv pre-commit
      - name: Sync dependencies with uv
        run: uv sync
      - name: Run pre-commit hooks
        run: pre-commit run --all-files

  test:
    name: Run pytest tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: Install uv
        run: |
          python -m pip install --upgrade pip
          pip install uv
      - name: Sync dependencies with uv
        run: uv sync
      - name: Run tests
        run: pytest
